Repository jenkinsci/gradle-plugin, pull requests merged in 2022-11, with the labels that each got.

#211 Revert jpi ext change
  acceptance-tests/build.gradle
  build.gradle
Labels: bugfix

#213 Update to Gradle Enterprise Maven extension 1.15.5
  README.adoc
  build.gradle
  configuration-maven-extension/build.gradle
  settings.gradle
  src/test/groovy/hudson/plugins/gradle/injection/InjectionConfigTest.groovy
Labels: dependencies

#215 Improve build scan link capturing
  src/main/java/hudson/plugins/gradle/BuildScanLogScanner.java
  src/test/groovy/hudson/plugins/gradle/BuildScanLogScannerTest.groovy
Labels: bugfix

#214 Skip auto-injection if older version of maven-plugin is used
  acceptance-tests/src/main/java/hudson/plugin/gradle/ath/config/GradleAcceptanceTestsModule.java
  acceptance-tests/src/main/java/hudson/plugin/gradle/ath/config/WorkspaceModule.java
  acceptance-tests/src/main/java/hudson/plugin/gradle/ath/updatecenter/VersionOverridesDecorator.java
  acceptance-tests/src/main/java/hudson/plugin/gradle/ath/updatecenter/WithVersionOverrides.java
  acceptance-tests/src/test/java/hudson/plugins/gradle/MavenInjectionTest.java
  build.gradle
  src/main/java/hudson/plugins/gradle/injection/InjectionUtil.java
  src/main/java/hudson/plugins/gradle/injection/maven/GradleEnterpriseExtensionsContributorFactory.java
Labels: bugfix

#216 Display auto-injection warning if the unsupported version of maven-pl…
  src/main/java/hudson/plugins/gradle/injection/InjectionConfig.java
  src/main/java/hudson/plugins/gradle/injection/UnsupportedMavenPluginWarningDetails.java
  src/main/java/hudson/plugins/gradle/injection/maven/GradleEnterpriseExtensionsContributorFactory.java
  src/main/resources/hudson/plugins/gradle/injection/InjectionConfig/config.jelly
Labels: feature
