Repository jenkinsci/gradle-plugin, pull requests merged in 2022-01, with the labels that each got.

#136 Remove line length limit for build scan message
  src/main/java/hudson/plugins/gradle/BuildScanLogScanner.java
  src/main/java/hudson/plugins/gradle/GradleConsoleAnnotator.java
Labels: bugfix

#75 Support variables in build file location
  src/main/java/hudson/plugins/gradle/Gradle.java
Labels: feature

#137 Upgrade jpi plugin to 0.43.0
  build.gradle
Labels: chore
