Repository jenkinsci/gradle-plugin, pull requests merged in 2022-10, with the labels that each got.

#186 Improve documentation
  README.adoc
  src/main/resources/hudson/plugins/gradle/BuildScanPublisher/help.html
  src/main/resources/hudson/plugins/gradle/Messages.properties
  src/main/resources/hudson/plugins/gradle/Messages_de.properties
Labels: documentation

#188 Update compatibility matrix during the release
  RELEASING.md
Labels: skip-changelog

#185 Form based injection configuration
  README.adoc
  acceptance-tests/build.gradle
  acceptance-tests/src/main/java/hudson/plugin/gradle/BuildScansInjectionSettings.java
  acceptance-tests/src/main/java/hudson/plugin/gradle/EnvironmentVariablesSettings.java
  acceptance-tests/src/test/java/hudson/plugins/gradle/AbstractAcceptanceTest.java
  acceptance-tests/src/test/java/hudson/plugins/gradle/GradleInjectionTest.java
  acceptance-tests/src/test/java/hudson/plugins/gradle/MavenInjectionTest.java
  build.gradle
  images/enable-auto-injection.png
  images/gradle-settings.png
  images/maven-settings.png
  src/main/java/hudson/plugins/gradle/injection/BuildScanEnvironmentContributor.java
  src/main/java/hudson/plugins/gradle/injection/BuildScanInjection.java
  src/main/java/hudson/plugins/gradle/injection/BuildScanInjectionListener.java
  src/main/java/hudson/plugins/gradle/injection/EnvUtil.java
  src/main/java/hudson/plugins/gradle/injection/GradleBuildScanInjection.java
  src/main/java/hudson/plugins/gradle/injection/GradleEnterpriseVersionValidator.java
  src/main/java/hudson/plugins/gradle/injection/HttpUrlValidator.java
  src/main/java/hudson/plugins/gradle/injection/InjectionConfig.java
  src/main/java/hudson/plugins/gradle/injection/InjectionUtil.java
  src/main/java/hudson/plugins/gradle/injection/InjectionUtils.java
  src/main/java/hudson/plugins/gradle/injection/MavenBuildScanInjection.java
  src/main/java/hudson/plugins/gradle/injection/MavenOptsSetter.java
  src/main/java/hudson/plugins/gradle/injection/NodeLabelItem.java
  src/main/java/hudson/plugins/gradle/injection/Validator.java
  src/main/java/hudson/plugins/gradle/util/CollectionUtil.java
  src/main/resources/hudson/plugins/gradle/Gradle/help-passAsProperties.html
  src/main/resources/hudson/plugins/gradle/Gradle/help-useWorkspaceAsHome.html
  src/main/resources/hudson/plugins/gradle/Messages.properties
  src/main/resources/hudson/plugins/gradle/injection/InjectionConfig/config.jelly
  src/main/resources/hudson/plugins/gradle/injection/InjectionConfig/help-accessKey.html
  src/main/resources/hudson/plugins/gradle/injection/InjectionConfig/help-allowUntrusted.html
  src/main/resources/hudson/plugins/gradle/injection/InjectionConfig/help-ccudPluginVersion.html
  src/main/resources/hudson/plugins/gradle/injection/InjectionConfig/help-gradlePluginRepositoryUrl.html
  src/main/resources/hudson/plugins/gradle/injection/InjectionConfig/help-gradlePluginVersion.html
  src/main/resources/hudson/plugins/gradle/injection/InjectionConfig/help-injectCcudExtension.html
  src/main/resources/hudson/plugins/gradle/injection/InjectionConfig/help-injectMavenExtension.html
  src/main/resources/hudson/plugins/gradle/injection/InjectionConfig/help-server.html
  src/main/resources/hudson/plugins/gradle/injection/NodeLabelItem/config.jelly
  src/main/webapp/help-gradleInjectionDisabledNodes.html
  src/main/webapp/help-gradleInjectionEnabledNodes.html
  src/main/webapp/help-mavenInjectionDisabledNodes.html
  src/main/webapp/help-mavenInjectionEnabledNodes.html
  src/test/groovy/hudson/plugins/gradle/AbstractIntegrationTest.groovy
  src/test/groovy/hudson/plugins/gradle/ConfigurationAsCodeTest.groovy
  src/test/groovy/hudson/plugins/gradle/injection/BaseGradleInjectionIntegrationTest.groovy
  src/test/groovy/hudson/plugins/gradle/injection/BaseInjectionIntegrationTest.groovy
  src/test/groovy/hudson/plugins/gradle/injection/BuildScanInjectionGradleIntegrationTest.groovy
  src/test/groovy/hudson/plugins/gradle/injection/BuildScanInjectionMavenCrossVersionTest.groovy
  src/test/groovy/hudson/plugins/gradle/injection/BuildScanInjectionMavenIntegrationTest.groovy
  src/test/groovy/hudson/plugins/gradle/injection/InjectionConfigTest.groovy
  src/test/groovy/hudson/plugins/gradle/injection/InjectionUtilTest.groovy
  src/test/groovy/hudson/plugins/gradle/injection/InjectionUtilsTest.groovy
Labels: feature

#189 Warning message is displayed if legacy environment variables are set
  README.adoc
  build.gradle
  images/find-build-scans.png
  images/gradle-build-step.png
  images/gradle-tool-installation.png
  images/inspect-logs-for-build-scans.png
  images/jenkins-build-scan.png
  images/pipeline-steps-scan.png
  src/main/java/hudson/plugins/gradle/injection/BuildScanInjectionListener.java
  src/main/java/hudson/plugins/gradle/injection/EnvUtil.java
  src/main/java/hudson/plugins/gradle/injection/InjectionConfig.java
  src/main/resources/hudson/plugins/gradle/injection/InjectionConfig/config.jelly
  src/test/groovy/hudson/plugins/gradle/injection/BuildScanInjectionGradleIntegrationTest.groovy
  src/test/groovy/hudson/plugins/gradle/injection/InjectionConfigTest.groovy
Labels: feature

#193 Fix roadmap section in the README
  README.adoc
Labels: skip-changelog

#201 Build Scans auto-injection support for maven-plugin
  acceptance-tests/src/test/java/hudson/plugins/gradle/MavenInjectionTest.java
  build.gradle
  configuration-maven-extension/build.gradle
  configuration-maven-extension/src/main/java/com/gradle/jenkins/maven/extension/internal/GradleEnterpriseConfigurerListener.java
  configuration-maven-extension/src/main/resources/META-INF/plexus/components.xml
  settings.gradle
  src/main/java/hudson/plugins/gradle/injection/EnvUtil.java
  src/main/java/hudson/plugins/gradle/injection/GradleBuildScanInjection.java
  src/main/java/hudson/plugins/gradle/injection/MavenBuildScanInjection.java
  src/main/java/hudson/plugins/gradle/injection/MavenExtensionsHandler.java
  src/main/java/hudson/plugins/gradle/injection/MavenOptsSetter.java
  src/main/java/hudson/plugins/gradle/injection/SystemProperty.java
  src/main/java/hudson/plugins/gradle/injection/maven/GradleEnterpriseExtensionsContributorFactory.java
  src/test/groovy/hudson/plugins/gradle/CliIntegrationTest.groovy
  src/test/groovy/hudson/plugins/gradle/CompatibilityTest.groovy
  src/test/groovy/hudson/plugins/gradle/GradlePluginIntegrationTest.groovy
  src/test/groovy/hudson/plugins/gradle/PropertyPassingIntegrationTest.groovy
  src/test/groovy/hudson/plugins/gradle/injection/BuildScanInjectionMavenIntegrationTest.groovy
Labels: feature

#203 Bump up acceptance test harness version
  acceptance-tests/build.gradle
  acceptance-tests/src/test/java/hudson/plugins/gradle/GradleInjectionTest.java
  acceptance-tests/src/test/java/hudson/plugins/gradle/MavenInjectionTest.java
Labels: dependencies

#202 Align static imports order between groovy and java sources
  config/codenarc/codenarc.xml
  src/test/groovy/hudson/plugins/gradle/GradlePluginIntegrationTest.groovy
  src/test/groovy/hudson/plugins/gradle/PropertyPassingIntegrationTest.groovy
  src/test/groovy/hudson/plugins/gradle/injection/BuildScanInjectionMavenIntegrationTest.groovy
Labels: skip-changelog
