Repository jenkinsci/gradle-plugin, pull requests merged in 2023-07, with the labels that each got.

#315 Bump CCUD Maven extension to 1.12.1
  settings.gradle.kts
Labels: dependencies

#314 Bump Gradle Wrapper from 8.1.1 to 8.2
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
Labels: dependencies

#318 [JENKINS-71509] Clean up of `GradleEnterpriseExceptionTaskListenerDecorator`
  src/main/java/hudson/plugins/gradle/injection/GradleEnterpriseExceptionLogFilter.java
  src/main/java/hudson/plugins/gradle/injection/GradleEnterpriseExceptionTaskListenerDecoratorFactory.java
  src/test/groovy/hudson/plugins/gradle/injection/BuildScanInjectionGradleWithDurableTaskStepUseWatchingIntegrationTest.groovy
  src/test/groovy/hudson/plugins/gradle/injection/GradleSnippets.groovy
Labels: bugfix

#320 Bump to latest GE components
  README.adoc
  settings.gradle.kts
Labels: dependencies

#324 Set `gradle.enterprise.externally-applied` before applying GE plugin
  src/main/resources/hudson/plugins/gradle/injection/init-script.gradle
Labels: enhancement

#325 Align init script with version in TeamCity plugin
  src/main/resources/hudson/plugins/gradle/injection/init-script.gradle
Labels: enhancement

#326 Update Gradle Enterprise Maven extension 1.18.1
  README.adoc
  settings.gradle.kts
Labels: dependencies

#327 Bump org.jenkins-ci:acceptance-test-harness from 5581.vfd8e43f46a_03 to 5668.vddb_c1150ef3d
  acceptance-tests/build.gradle.kts
Labels: dependencies
