Repository jenkinsci/gradle-plugin, pull requests merged in 2023-03, with the labels that each got.

#243 Update gradle to version 8.0.1
  gradle.properties
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle.kts
Labels: chore

#255 Bump up gradle to version 8.0.2
  gradle/wrapper/gradle-wrapper.properties
Labels: dependencies

#258 Do not set empty MAVEN_OPTS environment variable
  build.gradle.kts
  src/main/java/hudson/plugins/gradle/injection/EnvUtil.java
  src/main/java/hudson/plugins/gradle/injection/MavenBuildScanInjection.java
  src/main/java/hudson/plugins/gradle/injection/MavenOptsSetter.java
  src/main/java/hudson/plugins/gradle/injection/SystemProperty.java
  src/test/groovy/hudson/plugins/gradle/AbstractIntegrationTest.groovy
  src/test/groovy/hudson/plugins/gradle/injection/BuildScanInjectionMavenIntegrationTest.groovy
Labels: bugfix

#266 Configure depandabot to ignore maven-core versions update
  .github/dependabot.yml
Labels: dependencies

#268 Set overflow to auto to display scrollbar only when necessary
  src/main/resources/hudson/plugins/gradle/AbstractBuildScanAction/enriched-css.jelly
Labels: bugfix

#273 Upgrade embedded GE maven extension version to 1.16.6
  README.adoc
  settings.gradle.kts
Labels: dependencies
