Repository jenkinsci/gradle-plugin, pull requests merged in 2023-04, with the labels that each got.

#269 Move injection logic to EnvironmentContributor
  src/main/java/hudson/plugins/gradle/injection/BuildScanInjection.java
  src/main/java/hudson/plugins/gradle/injection/GradleBuildScanInjection.java
  src/main/java/hudson/plugins/gradle/injection/GradleInjectionAware.java
  src/main/java/hudson/plugins/gradle/injection/GradleInjectionEnvironmentContributor.java
  src/main/java/hudson/plugins/gradle/injection/MavenBuildScanInjection.java
  src/main/java/hudson/plugins/gradle/injection/MavenExtensionsHandler.java
  src/main/java/hudson/plugins/gradle/injection/MavenInjectionAware.java
  src/main/java/hudson/plugins/gradle/injection/MavenInjectionEnvironmentContributor.java
  src/main/java/hudson/plugins/gradle/injection/MavenInjectionRunListener.java
  src/main/java/hudson/plugins/gradle/injection/MavenOptsHandler.java
  src/main/java/hudson/plugins/gradle/injection/maven/GradleEnterpriseExtensionsContributorFactory.java
  src/main/resources/hudson/plugins/gradle/injection/init-script.gradle
  src/test/groovy/hudson/plugins/gradle/injection/BuildScanInjectionGradleIntegrationTest.groovy
  src/test/groovy/hudson/plugins/gradle/injection/BuildScanInjectionMavenCrossVersionTest.groovy
  src/test/groovy/hudson/plugins/gradle/injection/BuildScanInjectionMavenIntegrationTest.groovy
  src/test/groovy/hudson/plugins/gradle/injection/GradleInjectionEnvironmentContributorTest.groovy
  src/test/groovy/hudson/plugins/gradle/injection/MavenInjectionEnvironmentContributorTest.groovy
Labels: enhancement

#277 Fix the exist check of jar paths for maven-plugin
  build-logic/src/main/kotlin/buildlogic.chromedriver.gradle.kts
  src/main/java/hudson/plugins/gradle/injection/maven/GradleEnterpriseExtensionsContributorFactory.java
Labels: bugfix

#284 Do not use commons-lang3 when it is not available
  acceptance-tests/src/main/java/hudson/plugin/gradle/BuildScansInjectionSettings.java
  acceptance-tests/src/test/java/hudson/plugins/gradle/AbstractAcceptanceTest.java
  src/main/java/hudson/plugins/gradle/injection/GradleEnterpriseAccessKeyValidator.java
  src/main/java/hudson/plugins/gradle/injection/maven/GradleEnterpriseExtensionsContributorFactory.java
Labels: bugfix

#286 Bump Gradle Wrapper from 8.1 to 8.1.1
  gradle/wrapper/gradle-wrapper.properties
Labels: dependencies

#290 Ensure Gradle Enterprise access key is not shown in a plain text
  acceptance-tests/src/test/java/hudson/plugins/gradle/GradleInjectionTest.java
  src/main/java/hudson/plugins/gradle/AbstractLogger.java
  src/main/java/hudson/plugins/gradle/GradleEnterpriseLogger.java
  src/main/java/hudson/plugins/gradle/GradleLogger.java
  src/main/java/hudson/plugins/gradle/injection/BuildScanEnvironmentContributor.java
  src/test/groovy/hudson/plugins/gradle/AbstractIntegrationTest.groovy
  src/test/groovy/hudson/plugins/gradle/injection/BuildScanEnvironmentContributorTest.groovy
  src/test/groovy/hudson/plugins/gradle/injection/BuildScanInjectionGradleIntegrationTest.groovy
  src/test/groovy/hudson/plugins/gradle/injection/BuildScanInjectionMavenIntegrationTest.groovy
Labels: enhancement
