Repository jenkinsci/gradle-plugin, pull requests merged in 2023-02, with the labels that each got.

#236 Always perform a cleanup if auto-injection is disabled globally
  build.gradle.kts
  src/main/java/hudson/plugins/gradle/injection/BuildScanInjectionListener.java
  src/main/java/hudson/plugins/gradle/injection/GradleBuildScanInjection.java
  src/main/java/hudson/plugins/gradle/injection/GradleEnterpriseComputerListener.java
  src/main/java/hudson/plugins/gradle/injection/GradleEnterpriseInjector.java
  src/main/java/hudson/plugins/gradle/injection/InjectionConfig.java
  src/main/java/hudson/plugins/gradle/injection/InjectionConfigChangeListener.java
  src/main/java/hudson/plugins/gradle/injection/InjectionUtil.java
  src/main/java/hudson/plugins/gradle/injection/MavenBuildScanInjection.java
  src/test/groovy/hudson/plugins/gradle/GradleAbstractIntegrationTest.groovy
  src/test/groovy/hudson/plugins/gradle/injection/BuildScanInjectionGradleIntegrationTest.groovy
  src/test/groovy/hudson/plugins/gradle/injection/ExpectedException.java
  src/test/groovy/hudson/plugins/gradle/injection/GradleEnterpriseComputerListenerTest.groovy
  src/test/groovy/hudson/plugins/gradle/injection/InjectionConfigChangeListenerTest.groovy
Labels: bugfix

#238 Upgrade embedded maven extension version
  README.adoc
  settings.gradle.kts
Labels: dependencies

#232 Enriched build scans
  README.adoc
  acceptance-tests/src/main/java/hudson/plugin/gradle/BuildScansInjectionSettings.java
  acceptance-tests/src/test/java/hudson/plugins/gradle/AbstractAcceptanceTest.java
  acceptance-tests/src/test/java/hudson/plugins/gradle/GradleEnrichedScansTest.java
  acceptance-tests/src/test/java/hudson/plugins/gradle/GradleInjectionTest.java
  acceptance-tests/src/test/java/hudson/plugins/gradle/MavenEnrichedScansTest.java
  acceptance-tests/src/test/java/hudson/plugins/gradle/MockGeServer.java
  acceptance-tests/src/test/resources/mvn_extensions_with_ge.xml
  build.gradle.kts
  images/enriched-build-scans-configuration.png
  images/enriched-build-scans.png
  src/main/java/hudson/plugins/gradle/AbstractBuildScanAction.java
  src/main/java/hudson/plugins/gradle/BuildScanPublisher.java
  src/main/java/hudson/plugins/gradle/DefaultBuildScanPublishedListener.java
  src/main/java/hudson/plugins/gradle/Gradle.java
  src/main/java/hudson/plugins/gradle/GradleConsoleLogFilter.java
  src/main/java/hudson/plugins/gradle/WithGradleExecution.java
  src/main/java/hudson/plugins/gradle/enriched/EnrichedSummaryConfig.java
  src/main/java/hudson/plugins/gradle/enriched/HttpClientFactory.java
  src/main/java/hudson/plugins/gradle/enriched/ScanDetail.java
  src/main/java/hudson/plugins/gradle/enriched/ScanDetailService.java
  src/main/resources/hudson/plugins/gradle/AbstractBuildScanAction/enriched-css.jelly
  src/main/resources/hudson/plugins/gradle/AbstractBuildScanAction/index.jelly
  src/main/resources/hudson/plugins/gradle/AbstractBuildScanAction/summary.jelly
  src/main/resources/hudson/plugins/gradle/enriched/EnrichedSummaryConfig/config.jelly
  src/main/resources/hudson/plugins/gradle/enriched/EnrichedSummaryConfig/help-buildScanAccessKey.html
  src/main/resources/hudson/plugins/gradle/enriched/EnrichedSummaryConfig/help-buildScanServer.html
  src/main/resources/hudson/plugins/gradle/enriched/EnrichedSummaryConfig/help-enrichedSummaryEnabled.html
  src/main/resources/hudson/plugins/gradle/enriched/EnrichedSummaryConfig/help-httpClientDelayBetweenRetriesInSeconds.html
  src/main/resources/hudson/plugins/gradle/enriched/EnrichedSummaryConfig/help-httpClientMaxRetries.html
  src/main/resources/hudson/plugins/gradle/enriched/EnrichedSummaryConfig/help-httpClientTimeoutInSeconds.html
  src/main/resources/hudson/plugins/gradle/injection/InjectionConfig/help-injectionEnabled.html
  src/test/groovy/hudson/plugins/gradle/BuildScanActionTest.groovy
  src/test/groovy/hudson/plugins/gradle/enriched/EnrichedSummaryConfigTest.groovy
  src/test/groovy/hudson/plugins/gradle/enriched/ScanDetailServiceTest.groovy
Labels: feature

#242 Run acceptance tests only with the default jenkins version
  acceptance-tests/build.gradle.kts
  acceptance-tests/src/test/java/hudson/plugins/gradle/MockGeServer.java
Labels: chore

#248 Upgrade embedded GE maven extension version to 1.16.4
  README.adoc
  settings.gradle.kts
Labels: dependencies

#251 Fix typo in Enriched job summary table
  src/main/resources/hudson/plugins/gradle/AbstractBuildScanAction/summary.jelly
Labels: bugfix

#252 Fix typo in screenshot
  images/enriched-build-scans.png
Labels: skip-changelog

#253 Automatically download chrome driver when running on CI
  acceptance-tests/build.gradle.kts
  build-logic/src/main/kotlin/buildlogic.chromedriver.gradle.kts
Labels: chore
