Repository jenkinsci/gradle-plugin, pull requests merged in 2024-02, with the labels that each got.

#392 Change messages log level in init script
  src/main/resources/hudson/plugins/gradle/injection/init-script.gradle
  src/test/groovy/hudson/plugins/gradle/injection/BuildScanInjectionGradleIntegrationTest.groovy
Labels: enhancement

#394 Bump com.gradle:gradle-enterprise-maven-extension from 1.20 to 1.20.1
  README.adoc
  settings.gradle.kts
Labels: dependencies

#393 Apply Develocity Maven extension only if not already applied
  src/main/java/hudson/plugins/gradle/injection/GitScmListener.java
  src/main/java/hudson/plugins/gradle/injection/MavenCoordinates.java
  src/main/java/hudson/plugins/gradle/injection/MavenExtensions.java
  src/test/groovy/hudson/plugins/gradle/BaseGradleIntegrationTest.groovy
  src/test/groovy/hudson/plugins/gradle/injection/BuildScanInjectionGradleIntegrationTest.groovy
  src/test/groovy/hudson/plugins/gradle/injection/BuildScanInjectionGradleWithDurableTaskStepUseWatchingIntegrationTest.groovy
  src/test/groovy/hudson/plugins/gradle/injection/BuildScanInjectionMavenCrossVersionTest.groovy
  src/test/groovy/hudson/plugins/gradle/injection/BuildScanInjectionMavenIntegrationTest.groovy
  src/test/groovy/hudson/plugins/gradle/injection/MavenExtensionsTest.groovy
Labels: enhancement

#398 Disable injection when custom extensions are detected
  src/main/java/hudson/plugins/gradle/injection/GitScmListener.java
  src/main/java/hudson/plugins/gradle/injection/InjectionConfig.java
  src/main/java/hudson/plugins/gradle/injection/MavenBuildScanInjection.java
  src/main/java/hudson/plugins/gradle/injection/MavenCoordinates.java
  src/main/java/hudson/plugins/gradle/injection/MavenExtClasspathUtils.java
  src/main/java/hudson/plugins/gradle/injection/MavenExtension.java
  src/main/java/hudson/plugins/gradle/injection/MavenExtensions.java
  src/main/java/hudson/plugins/gradle/injection/MavenExtensionsDetector.java
  src/main/java/hudson/plugins/gradle/injection/MavenExtensionsHandler.java
  src/main/java/hudson/plugins/gradle/injection/MavenOptsDevelocityFilter.java
  src/main/java/hudson/plugins/gradle/injection/SystemProperty.java
  src/main/resources/hudson/plugins/gradle/Messages.properties
  src/main/resources/hudson/plugins/gradle/injection/InjectionConfig/config.jelly
  src/main/resources/hudson/plugins/gradle/injection/InjectionConfig/help-ccudExtensionCustomCoordinates.html
  src/main/resources/hudson/plugins/gradle/injection/InjectionConfig/help-mavenExtensionCustomCoordinates.html
  src/test/groovy/hudson/plugins/gradle/injection/BuildScanInjectionMavenIntegrationTest.groovy
  src/test/groovy/hudson/plugins/gradle/injection/MavenCoordinatesTest.groovy
  src/test/groovy/hudson/plugins/gradle/injection/MavenExtensionsDetectorTest.groovy
  src/test/groovy/hudson/plugins/gradle/injection/MavenExtensionsHandlerTest.groovy
  src/test/groovy/hudson/plugins/gradle/injection/MavenExtensionsTest.groovy
  src/test/groovy/hudson/plugins/gradle/injection/MavenOptsDevelocityFilterTest.groovy
  src/test/groovy/hudson/plugins/gradle/injection/SystemPropertyTest.groovy
Labels: feature
