Repository jenkinsci/gradle-plugin, pull requests merged in 2024-09, with the labels that each got.

#476 Download Maven extensions instead of bundling them
  README.adoc
  acceptance-tests/src/main/java/hudson/plugin/gradle/BuildScansInjectionSettings.java
  acceptance-tests/src/test/java/hudson/plugins/gradle/AbstractAcceptanceTest.java
  acceptance-tests/src/test/java/hudson/plugins/gradle/GradleInjectionTest.java
  build.gradle.kts
  configuration-maven-extension/build.gradle.kts
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  settings.gradle.kts
  src/main/java/hudson/plugins/gradle/injection/GitScmListener.java
  src/main/java/hudson/plugins/gradle/injection/InjectionConfig.java
  src/main/java/hudson/plugins/gradle/injection/MavenBuildScanInjection.java
  src/main/java/hudson/plugins/gradle/injection/MavenExtension.java
  src/main/java/hudson/plugins/gradle/injection/MavenExtensionsDetector.java
  src/main/java/hudson/plugins/gradle/injection/MavenExtensionsHandler.java
  src/main/java/hudson/plugins/gradle/injection/MavenInjectionAware.java
  src/main/java/hudson/plugins/gradle/injection/extension/ExtensionClient.java
  src/main/java/hudson/plugins/gradle/injection/token/ShortLivedTokenClient.java
  src/main/resources/hudson/plugins/gradle/injection/InjectionConfig/config.jelly
  src/main/resources/hudson/plugins/gradle/injection/InjectionConfig/help-ccudExtensionVersion.html
  src/main/resources/hudson/plugins/gradle/injection/InjectionConfig/help-injectCcudExtension.html
  src/main/resources/hudson/plugins/gradle/injection/InjectionConfig/help-injectMavenExtension.html
  src/main/resources/hudson/plugins/gradle/injection/InjectionConfig/help-mavenExtensionVersion.html
  src/test/groovy/hudson/plugins/gradle/injection/BuildScanInjectionMavenCrossVersionTest.groovy
  src/test/groovy/hudson/plugins/gradle/injection/BuildScanInjectionMavenIntegrationTest.groovy
  src/test/groovy/hudson/plugins/gradle/injection/InjectionConfigTest.groovy
  src/test/groovy/hudson/plugins/gradle/injection/MavenExtensionsDetectorTest.groovy
  src/test/groovy/hudson/plugins/gradle/injection/MavenExtensionsHandlerTest.groovy
Labels: enhancement

#480 Bump references to Common Custom User Data Maven extension from 2.0 to 2.0.1
  README.adoc
Labels: dependencies

#485 Save the configuration after migration is done
  src/main/java/hudson/plugins/gradle/injection/InjectionConfig.java
Labels: bugfix

#481 Update README
  README.adoc
  images/enable-auto-injection.png
  images/gradle-settings.png
  images/maven-settings.png
Labels: documentation
